# Dicom setting
dcm_win_center: 40
dcm_win_width: 350
# Dataset
data_type: "Pancreas_2d"
data_mode: 'img'
train_mode: 'train'
test_mode: 'val'
data_root: './data'
split_info: './data/splits/train_val_test_2d_v1.json'
cls_anno_path: './data/pancreas/anno_all.json'

test_image_dir: './data/pancreas/images_3d'
test_dcm_dir: './data/pancreas/dcms_3d'
test_anno_path: ''

batch_size: 16
num_worker: 8
drop_last: True

# Augmentation
rescale: [560,560]
rand_rotate: ""
rand_scale: ""
crop_window: [512, 512]
crop_size: [512,512]
rand_blood_text: False
rand_others_text: False
window_crop: False
## 3D
D_center_ratio: 0.5
D_offset_ratio: 0.1
D_center_window: 64
## 2D
neighbour_slice: True

# Net
net_resume: ''
# Image Encoder
net_name: 'resnet'
net_backbone: 'resnet50'
net_pretrain: ''
# Text Encoder
net_blood_name: "mlp"
net_others_name: "transformer"
net_text_pretrain: 'CLIP_ViT-B/32' # 'CLIP_ViT-L/14'
# Classifiers
net_dropout: 0.5
net_classifier_inchannel: 640
net_essential_classes: 2
net_invade_classes: 2
net_surgery_classes: 2
net_seg_classes: 3
net_nheads: 1
net_num_iter: 3000
net_learning_rate: 0.001
net_cls_use_essential: True
net_seg_use_essential: True
net_invade_cls_celoss: True
net_surgery_cls_celoss: True
net_essential_cls_celoss: True
net_seg_celoss: False

# Training
two_stage: False
stage_thres: 0.95

# Inference
test_fusion: 'mean'
main_metric: 'test_avg'
test_checkpoint: 'best_model.pth'

## 2D
vote_mode: 'pred_essential'
score_mode: 'max'

# Saving
workspace: './workspace/2D_final/res50_mlp_trans_iter3000_img_b16_rz560_crp512_ecs_d0.5'
results_val: 'results_val'
results_test: 'results_test'
checkpoint: best_epoch.pth
val_interval: 100
save_interval: 1000

